const router = require("express").Router();
const authRoutes = require("./auth-routes");
const adminRoutes = require("./admin-routes");
const categoriesRoutes = require("./categories-routes");
const commentsRoutes = require("./comments-routes");
const profileRoutes = require("./profile-routes");
const storiesRoutes = require("./stories-routes");
const videosRoutes = require("./videos-routes");
const doctorRoutes = require("./doctor-routes");
const packageRoutes = require("./package-routes");
const departmentRoutes = require("./department-routes");
const galleryRoutes = require("./gallery-routes");
const homeRoutes = require("./home-routes");
const healthRoutes = require("./health-routes");
const variantRoutes = require("./variant-routes");
const aboutUsRoutes = require("./about-us-routes");
const goalsRoutes = require("./goals-routes");
const patientRightRoutes = require("./patient-rights-routes");
const insuranceRoutes = require("./insurance-routes");
const contactRoutes = require("./contact-routes");
const privacyRoutes = require("./privacy-routes");
const termsRoutes = require("./terms-routes");
const mastercardRoutes = require("./mastercard-routes");

router.use("/auth", authRoutes);
router.use("/api", adminRoutes);
router.use("/api", categoriesRoutes);
router.use("/api", commentsRoutes);
router.use("/api", profileRoutes);
router.use("/api", storiesRoutes);
router.use("/api", videosRoutes);
router.use("/api", doctorRoutes);
router.use("/api", packageRoutes);
router.use("/api", departmentRoutes);
router.use("/api", galleryRoutes);
router.use("/api", homeRoutes);
router.use("/api", healthRoutes);
router.use("/api", variantRoutes);
router.use("/api", aboutUsRoutes);
router.use("/api", goalsRoutes);
router.use("/api", patientRightRoutes);
router.use("/api", contactRoutes);
router.use("/api", insuranceRoutes);
router.use("/api", privacyRoutes);
router.use("/api", termsRoutes);
router.use("/api", mastercardRoutes);

module.exports = router;
