export const patients = [
  {
    id: 1,
    address: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    avatarUrl: "/static/images/avatars/avatar_3.png",
    createdAt: "12/04/2019",
    email: "ekaterina.tankova@akmc.com",
    name: "Ekaterina Tankova",
    phone: "304-428-3097",
  },
  {
    id: 2,
    address: {
      country: "USA",
      state: "Bristow",
      city: "Iowa",
      street: "1865  Pleasant Hill Road",
    },
    avatarUrl: "/static/images/avatars/avatar_4.png",
    createdAt: "12/04/2019",
    email: "cao.yu@akmc.com",
    name: "Cao Yu",
    phone: "712-351-5711",
  },
  {
    id: 3,
    address: {
      country: "USA",
      state: "Georgia",
      city: "Atlanta",
      street: "4894  Lakeland Park Drive",
    },
    avatarUrl: "/static/images/avatars/avatar_2.png",
    createdAt: "12/04/2019",
    email: "alexa.richardson@akmc.com",
    name: "Alexa Richardson",
    phone: "770-635-2682",
  },
  {
    id: 4,
    address: {
      country: "USA",
      state: "Ohio",
      city: "Dover",
      street: "4158  Hedge Street",
    },
    avatarUrl: "/static/images/avatars/avatar_5.png",
    createdAt: "11/04/2019",
    email: "anje.keizer@akmc.com",
    name: "Anje Keizer",
    phone: "908-691-3242",
  },
  {
    id: 5,
    address: {
      country: "USA",
      state: "Texas",
      city: "Dallas",
      street: "75247",
    },
    avatarUrl: "/static/images/avatars/avatar_6.png",
    createdAt: "09/04/2019",
    email: "clarke.gillebert@akmc.com",
    name: "Clarke Gillebert",
    phone: "972-333-4106",
  },
  {
    id: 6,
    address: {
      country: "USA",
      state: "California",
      city: "Bakerfield",
      street: "317 Angus Road",
    },
    avatarUrl: "/static/images/avatars/avatar_1.png",
    createdAt: "08/04/2019",
    email: "adam.denisov@akmc.com",
    name: "Adam Denisov",
    phone: "858-602-3409",
  },
  {
    id: 7,
    address: {
      country: "USA",
      state: "California",
      city: "Redondo Beach",
      street: "2188  Armbrester Drive",
    },
    avatarUrl: "/static/images/avatars/avatar_7.png",
    createdAt: "04/04/2019",
    email: "ava.gregoraci@akmc.com",
    name: "Ava Gregoraci",
    phone: "415-907-2647",
  },
  {
    id: 8,
    address: {
      country: "USA",
      state: "Nevada",
      city: "Las Vegas",
      street: "1798  Hickory Ridge Drive",
    },
    avatarUrl: "/static/images/avatars/avatar_8.png",
    createdAt: "07/04/2018",
    email: "emilee.simchenko@akmc.com",
    name: "Emilee Simchenko",
    phone: "702-661-1654",
  },
  {
    id: 9,
    address: {
      country: "USA",
      state: "Michigan",
      city: "Detroit",
      street: "3934  Wildrose Lane",
    },
    avatarUrl: "/static/images/avatars/avatar_9.png",
    createdAt: "08/04/2019",
    email: "kwak.seong.min@akmc.com",
    name: "Kwak Seong-Min",
    phone: "313-812-8947",
  },
  {
    id: 10,
    address: {
      country: "USA",
      state: "Utah",
      city: "Salt Lake City",
      street: "368 Lamberts Branch Road",
    },
    avatarUrl: "/static/images/avatars/avatar_10.png",
    createdAt: "03/04/2018",
    email: "merrile.burgett@akmc.com",
    name: "Merrile Burgett",
    phone: "801-301-7894",
  },
];
